# Generated by Django 4.0.2 on 2022-02-09 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vdo', '0006_comment_video_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='rating',
        ),
    ]
