# Generated by Django 4.0.2 on 2022-02-09 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vdo', '0008_alter_comment_user_uploadedvideo_playlistvideo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_video', to='vdo.uploadedvideo'),
        ),
    ]
